apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: proxyconfigs.config.maestro.io
spec:
  group: config.maestro.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                resourceVersion:
                  type: string
      subresources:
        status: {}
  names:
    kind: ProxyConfig
    singular: proxyconfig
    plural: proxyconfigs
  scope: Namespaced
