// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: maestro/config/v1/proxy_config.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyConfig) Reset() {
	*x = ProxyConfig{}
	mi := &file_maestro_config_v1_proxy_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConfig) ProtoMessage() {}

func (x *ProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_maestro_config_v1_proxy_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConfig.ProtoReflect.Descriptor instead.
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return file_maestro_config_v1_proxy_config_proto_rawDescGZIP(), []int{0}
}

var File_maestro_config_v1_proxy_config_proto protoreflect.FileDescriptor

const file_maestro_config_v1_proxy_config_proto_rawDesc = "" +
	"\n" +
	"$maestro/config/v1/proxy_config.proto\x12\x11maestro.config.v1\"\r\n" +
	"\vProxyConfigB4Z2github.com/bpalermo/maestro/api/config/v1;configv1b\x06proto3"

var (
	file_maestro_config_v1_proxy_config_proto_rawDescOnce sync.Once
	file_maestro_config_v1_proxy_config_proto_rawDescData []byte
)

func file_maestro_config_v1_proxy_config_proto_rawDescGZIP() []byte {
	file_maestro_config_v1_proxy_config_proto_rawDescOnce.Do(func() {
		file_maestro_config_v1_proxy_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_maestro_config_v1_proxy_config_proto_rawDesc), len(file_maestro_config_v1_proxy_config_proto_rawDesc)))
	})
	return file_maestro_config_v1_proxy_config_proto_rawDescData
}

var file_maestro_config_v1_proxy_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_maestro_config_v1_proxy_config_proto_goTypes = []any{
	(*ProxyConfig)(nil), // 0: maestro.config.v1.ProxyConfig
}
var file_maestro_config_v1_proxy_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_maestro_config_v1_proxy_config_proto_init() }
func file_maestro_config_v1_proxy_config_proto_init() {
	if File_maestro_config_v1_proxy_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maestro_config_v1_proxy_config_proto_rawDesc), len(file_maestro_config_v1_proxy_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_maestro_config_v1_proxy_config_proto_goTypes,
		DependencyIndexes: file_maestro_config_v1_proxy_config_proto_depIdxs,
		MessageInfos:      file_maestro_config_v1_proxy_config_proto_msgTypes,
	}.Build()
	File_maestro_config_v1_proxy_config_proto = out.File
	file_maestro_config_v1_proxy_config_proto_goTypes = nil
	file_maestro_config_v1_proxy_config_proto_depIdxs = nil
}
