---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: maestro
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: maestro
          image: ghcr.io/bpalermo/maestro:latest

      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.32.4
          imagePullPolicy: Always
          args: ["-l", "debug", "--local-address-ip-version", "v4", "-c", "/etc/envoy/envoy.yaml"]
          ports:
            - name: http
              containerPort: 18080
            - name: admin
              containerPort: 9901
          volumeMounts:
            - name: envoy-config
              mountPath: "/etc/envoy"
              readOnly: true
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
        - name: opa
          image: openpolicyagent/opa:1.3.0-envoy
          imagePullPolicy: IfNotPresent
          ports:
            - name: opa-envoy
              containerPort: 8182
              protocol: TCP
            - name: opa-api-port
              containerPort: 8181
              protocol: TCP
          args:
            - "run"
            - "--server"
            - "--config-file=/run/opa/opa-config.yaml"
            - "/run/opa/opa-policy.rego"
          volumeMounts:
            - name: backend-opa-policy
              mountPath: /run/opa
              readOnly: true
      volumes:
        - name: envoy-config
          configMap:
            name: backend-envoy
        - name: backend-opa-policy
          configMap:
            name: backend-opa-policy-config
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: backend-balance-json-data
          configMap:
            name: backend-balance-json-data
        - name: backend-profile-json-data
          configMap:
            name: backend-profile-json-data
        - name: backend-transactions-json-data
          configMap:
            name: backend-transactions-json-data
