// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package configv1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for AuthZ
func (this *AuthZ) MarshalJSON() ([]byte, error) {
	str, err := AuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AuthZ
func (this *AuthZ) UnmarshalJSON(b []byte) error {
	return AuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	AuthzMarshaler   = &jsonpb.Marshaler{}
	AuthzUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
