// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package configv1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for AuthN
func (this *AuthN) MarshalJSON() ([]byte, error) {
	str, err := AuthnMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AuthN
func (this *AuthN) UnmarshalJSON(b []byte) error {
	return AuthnUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	AuthnMarshaler   = &jsonpb.Marshaler{}
	AuthnUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
