// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package configv1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using AuthZ within kubernetes types, where deepcopy-gen is used.
func (in *AuthZ) DeepCopyInto(out *AuthZ) {
	p := proto.Clone(in).(*AuthZ)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthZ. Required by controller-gen.
func (in *AuthZ) DeepCopy() *AuthZ {
	if in == nil {
		return nil
	}
	out := new(AuthZ)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AuthZ. Required by controller-gen.
func (in *AuthZ) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
