// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package configv1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using AuthN within kubernetes types, where deepcopy-gen is used.
func (in *AuthN) DeepCopyInto(out *AuthN) {
	p := proto.Clone(in).(*AuthN)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthN. Required by controller-gen.
func (in *AuthN) DeepCopy() *AuthN {
	if in == nil {
		return nil
	}
	out := new(AuthN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AuthN. Required by controller-gen.
func (in *AuthN) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
