// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config/v1/cors.proto

package configv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CORS with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *CORS) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CORS with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CORSMultiError, or nil if none found.
func (m *CORS) ValidateAll() error {
	return m.validate(true)
}

func (m *CORS) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CORSMultiError(errors)
	}

	return nil
}

// CORSMultiError is an error wrapping multiple validation errors returned by
// CORS.ValidateAll() if the designated constraints aren't met.
type CORSMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CORSMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CORSMultiError) AllErrors() []error { return m }

// CORSValidationError is the validation error returned by CORS.Validate if the
// designated constraints aren't met.
type CORSValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CORSValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CORSValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CORSValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CORSValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CORSValidationError) ErrorName() string { return "CORSValidationError" }

// Error satisfies the builtin error interface
func (e CORSValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCORS.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CORSValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CORSValidationError{}
