// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package configv1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for CORS
func (this *CORS) MarshalJSON() ([]byte, error) {
	str, err := CorsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CORS
func (this *CORS) UnmarshalJSON(b []byte) error {
	return CorsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	CorsMarshaler   = &jsonpb.Marshaler{}
	CorsUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
