// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package configv1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using CORS within kubernetes types, where deepcopy-gen is used.
func (in *CORS) DeepCopyInto(out *CORS) {
	p := proto.Clone(in).(*CORS)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CORS. Required by controller-gen.
func (in *CORS) DeepCopy() *CORS {
	if in == nil {
		return nil
	}
	out := new(CORS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CORS. Required by controller-gen.
func (in *CORS) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
