// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package configv1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Service within kubernetes types, where deepcopy-gen is used.
func (in *Service) DeepCopyInto(out *Service) {
	p := proto.Clone(in).(*Service)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service. Required by controller-gen.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Service. Required by controller-gen.
func (in *Service) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Service_ServicePort within kubernetes types, where deepcopy-gen is used.
func (in *Service_ServicePort) DeepCopyInto(out *Service_ServicePort) {
	p := proto.Clone(in).(*Service_ServicePort)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service_ServicePort. Required by controller-gen.
func (in *Service_ServicePort) DeepCopy() *Service_ServicePort {
	if in == nil {
		return nil
	}
	out := new(Service_ServicePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Service_ServicePort. Required by controller-gen.
func (in *Service_ServicePort) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Service_ServicePort_HttpHealthCheck within kubernetes types, where deepcopy-gen is used.
func (in *Service_ServicePort_HttpHealthCheck) DeepCopyInto(out *Service_ServicePort_HttpHealthCheck) {
	p := proto.Clone(in).(*Service_ServicePort_HttpHealthCheck)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service_ServicePort_HttpHealthCheck. Required by controller-gen.
func (in *Service_ServicePort_HttpHealthCheck) DeepCopy() *Service_ServicePort_HttpHealthCheck {
	if in == nil {
		return nil
	}
	out := new(Service_ServicePort_HttpHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Service_ServicePort_HttpHealthCheck. Required by controller-gen.
func (in *Service_ServicePort_HttpHealthCheck) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
