// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: config/v1/service.proto

package configv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ServicePorts  []*Service_ServicePort `protobuf:"bytes,2,rep,name=service_ports,json=servicePorts,proto3" json:"service_ports,omitempty"`
	Authn         *AuthN                 `protobuf:"bytes,3,opt,name=authn,proto3" json:"authn,omitempty"`
	Authz         *AuthZ                 `protobuf:"bytes,4,opt,name=authz,proto3" json:"authz,omitempty"`
	Cors          *CORS                  `protobuf:"bytes,5,opt,name=cors,proto3" json:"cors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_config_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_config_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetServicePorts() []*Service_ServicePort {
	if x != nil {
		return x.ServicePorts
	}
	return nil
}

func (x *Service) GetAuthn() *AuthN {
	if x != nil {
		return x.Authn
	}
	return nil
}

func (x *Service) GetAuthz() *AuthZ {
	if x != nil {
		return x.Authz
	}
	return nil
}

func (x *Service) GetCors() *CORS {
	if x != nil {
		return x.Cors
	}
	return nil
}

type Service_ServicePort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Port  uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// Types that are valid to be assigned to HealthCheckSpecifier:
	//
	//	*Service_ServicePort_HttpHealthCheck_
	HealthCheckSpecifier isService_ServicePort_HealthCheckSpecifier `protobuf_oneof:"health_check_specifier"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Service_ServicePort) Reset() {
	*x = Service_ServicePort{}
	mi := &file_config_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service_ServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service_ServicePort) ProtoMessage() {}

func (x *Service_ServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service_ServicePort.ProtoReflect.Descriptor instead.
func (*Service_ServicePort) Descriptor() ([]byte, []int) {
	return file_config_v1_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Service_ServicePort) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Service_ServicePort) GetHealthCheckSpecifier() isService_ServicePort_HealthCheckSpecifier {
	if x != nil {
		return x.HealthCheckSpecifier
	}
	return nil
}

func (x *Service_ServicePort) GetHttpHealthCheck() *Service_ServicePort_HttpHealthCheck {
	if x != nil {
		if x, ok := x.HealthCheckSpecifier.(*Service_ServicePort_HttpHealthCheck_); ok {
			return x.HttpHealthCheck
		}
	}
	return nil
}

type isService_ServicePort_HealthCheckSpecifier interface {
	isService_ServicePort_HealthCheckSpecifier()
}

type Service_ServicePort_HttpHealthCheck_ struct {
	HttpHealthCheck *Service_ServicePort_HttpHealthCheck `protobuf:"bytes,2,opt,name=http_health_check,json=httpHealthCheck,proto3,oneof"`
}

func (*Service_ServicePort_HttpHealthCheck_) isService_ServicePort_HealthCheckSpecifier() {}

type Service_ServicePort_HttpHealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service_ServicePort_HttpHealthCheck) Reset() {
	*x = Service_ServicePort_HttpHealthCheck{}
	mi := &file_config_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service_ServicePort_HttpHealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service_ServicePort_HttpHealthCheck) ProtoMessage() {}

func (x *Service_ServicePort_HttpHealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service_ServicePort_HttpHealthCheck.ProtoReflect.Descriptor instead.
func (*Service_ServicePort_HttpHealthCheck) Descriptor() ([]byte, []int) {
	return file_config_v1_service_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Service_ServicePort_HttpHealthCheck) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_config_v1_service_proto protoreflect.FileDescriptor

const file_config_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x17config/v1/service.proto\x12\tconfig.v1\x1a\x1bbuf/validate/validate.proto\x1a\x15config/v1/authn.proto\x1a\x15config/v1/authz.proto\x1a\x14config/v1/cors.proto\"\xe4\x04\n" +
	"\aService\x12\xc0\x01\n" +
	"\x04name\x18\x01 \x01(\tB\xab\x01\xbaH\xa7\x01\xba\x01O\n" +
	"\x13hostname.ishostname\x12%service name must be a valid hostname\x1a\x11this.isHostname()\xba\x01N\n" +
	"\x15hostname.notlocalhost\x12 service name connot be localhost\x1a\x13this != 'localhost'r\x02\x10\x01R\x04name\x12M\n" +
	"\rservice_ports\x18\x02 \x03(\v2\x1e.config.v1.Service.ServicePortB\b\xbaH\x05\x92\x01\x02\b\x01R\fservicePorts\x12&\n" +
	"\x05authn\x18\x03 \x01(\v2\x10.config.v1.AuthNR\x05authn\x12&\n" +
	"\x05authz\x18\x04 \x01(\v2\x10.config.v1.AuthZR\x05authz\x12#\n" +
	"\x04cors\x18\x05 \x01(\v2\x0f.config.v1.CORSR\x04cors\x1a\xd1\x01\n" +
	"\vServicePort\x12\x1c\n" +
	"\x04port\x18\x01 \x01(\rB\b\xbaH\x05*\x03 \x80\bR\x04port\x12\\\n" +
	"\x11http_health_check\x18\x02 \x01(\v2..config.v1.Service.ServicePort.HttpHealthCheckH\x00R\x0fhttpHealthCheck\x1a%\n" +
	"\x0fHttpHealthCheck\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04pathB\x1f\n" +
	"\x16health_check_specifier\x12\x05\xbaH\x02\b\x01B\x96\x01\n" +
	"\rcom.config.v1B\fServiceProtoP\x01Z2github.com/bpalermo/maestro/api/config/v1;configv1\xa2\x02\x03CXX\xaa\x02\tConfig.V1\xca\x02\tConfig\\V1\xe2\x02\x15Config\\V1\\GPBMetadata\xea\x02\n" +
	"Config::V1b\x06proto3"

var (
	file_config_v1_service_proto_rawDescOnce sync.Once
	file_config_v1_service_proto_rawDescData []byte
)

func file_config_v1_service_proto_rawDescGZIP() []byte {
	file_config_v1_service_proto_rawDescOnce.Do(func() {
		file_config_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_service_proto_rawDesc), len(file_config_v1_service_proto_rawDesc)))
	})
	return file_config_v1_service_proto_rawDescData
}

var file_config_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_config_v1_service_proto_goTypes = []any{
	(*Service)(nil),                             // 0: config.v1.Service
	(*Service_ServicePort)(nil),                 // 1: config.v1.Service.ServicePort
	(*Service_ServicePort_HttpHealthCheck)(nil), // 2: config.v1.Service.ServicePort.HttpHealthCheck
	(*AuthN)(nil),                               // 3: config.v1.AuthN
	(*AuthZ)(nil),                               // 4: config.v1.AuthZ
	(*CORS)(nil),                                // 5: config.v1.CORS
}
var file_config_v1_service_proto_depIdxs = []int32{
	1, // 0: config.v1.Service.service_ports:type_name -> config.v1.Service.ServicePort
	3, // 1: config.v1.Service.authn:type_name -> config.v1.AuthN
	4, // 2: config.v1.Service.authz:type_name -> config.v1.AuthZ
	5, // 3: config.v1.Service.cors:type_name -> config.v1.CORS
	2, // 4: config.v1.Service.ServicePort.http_health_check:type_name -> config.v1.Service.ServicePort.HttpHealthCheck
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_config_v1_service_proto_init() }
func file_config_v1_service_proto_init() {
	if File_config_v1_service_proto != nil {
		return
	}
	file_config_v1_authn_proto_init()
	file_config_v1_authz_proto_init()
	file_config_v1_cors_proto_init()
	file_config_v1_service_proto_msgTypes[1].OneofWrappers = []any{
		(*Service_ServicePort_HttpHealthCheck_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_service_proto_rawDesc), len(file_config_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v1_service_proto_goTypes,
		DependencyIndexes: file_config_v1_service_proto_depIdxs,
		MessageInfos:      file_config_v1_service_proto_msgTypes,
	}.Build()
	File_config_v1_service_proto = out.File
	file_config_v1_service_proto_goTypes = nil
	file_config_v1_service_proto_depIdxs = nil
}
