// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package configv1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Service
func (this *Service) MarshalJSON() ([]byte, error) {
	str, err := ServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Service
func (this *Service) UnmarshalJSON(b []byte) error {
	return ServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Service_ServicePort
func (this *Service_ServicePort) MarshalJSON() ([]byte, error) {
	str, err := ServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Service_ServicePort
func (this *Service_ServicePort) UnmarshalJSON(b []byte) error {
	return ServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Service_ServicePort_HttpHealthCheck
func (this *Service_ServicePort_HttpHealthCheck) MarshalJSON() ([]byte, error) {
	str, err := ServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Service_ServicePort_HttpHealthCheck
func (this *Service_ServicePort_HttpHealthCheck) UnmarshalJSON(b []byte) error {
	return ServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ServiceMarshaler   = &jsonpb.Marshaler{}
	ServiceUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
