// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package controllerv1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for ProxyConfig
func (this *ProxyConfig) MarshalJSON() ([]byte, error) {
	str, err := ProxyConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ProxyConfig
func (this *ProxyConfig) UnmarshalJSON(b []byte) error {
	return ProxyConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ProxyConfigMarshaler   = &jsonpb.Marshaler{}
	ProxyConfigUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
