name: ci

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  lint:
    name: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
