name: ci

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  lint:
    name: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v ./...
      - name: Run tests
        run: go test -race -vet=off ./...
